= Hardware specifications

Where did your run your tests? A laptop, or goldengate?
  I ran my tests on goldengate.

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)
  Number of processors: 64
  Speed of processors: 1200.063 MHz
  Size of RAM: 97608472 kB or about 97 GB 

= Allocations

In `simple.c`, where does the increase in 1040 bytes come from?
Why is the value 1040 bytes?
  The increase in 1040 bytes comes from the buffer along with the pointers for
  the two sbrk(0) calls, *init and *current. The value is 1040 bytes because the
  buffer is 1024 bytes in size and each pointer is 8 bytes in size. 
  So, 1024 bytes + 8 bytes + 8 bytes = 1040 bytes.
  The increase in 1040 bytes comes from the buffer/bytes for the print and the 
  bytes for the chunk header. The value is 1040 bytes because 1024 bytes is for 
  the print and 16 bytes are for the chunk header.
  So, 1024 bytes + 16 bytes = 1040 bytes.

How many bytes does `mylloc_list.c` allocate when the program ends? Explain why
this amount makes sense.
  'mylloc_list.c' allocates 1156 bytes total. This amount makes sense because
  1024 bytes are for the print, 2*16 for the chunk struct (so 32 bytes), and
  100 bytes for the malloc'd size.
  So, then 1024 bytes + 32 bytes + 100 bytes = 1156 bytes allocated in total when
  the program ends. 
  
  'mylloc_list.c' 

= Fragementation

What is fragmentation? What is the difference between internal and external
fragmentation?
  Fragmentation is when a memory allocation fails due to the specified amount of
  memory asked to be allocated being greater than the continguous block/chunk
  available or when memory is allocated in a large number of blocks/chunks 
  leaving a lot of the total memory unallocated, creating memory exceptions or
  allocation errors. The differences between internal and external fragmentation
  is that internal fragmentation is when the memory space is larger than what is
  requested, so there is space in a block/chunk that is unused so the chunks are
  too large. On the other hand, opposite to internal, external fragmentation is
  when the chunks are too small. Where the chunks are divided into too many small
  chunks thateven with a lot of free space, the memory allocation won't work due
  to the small chunks making it non-continguous. (A solution to these
  fragmentations being splitting andi/or merging.)

Include your output in the README.adoc
  My output for benchmark2 is (resubmitted version, so my new output! :D):
The initial top of the heap is 0x7f109ddca000.
Total blocks: 161 Free: 103 Used: 58
Internal unused: total: 1826304 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 144345 average: 1401.0 smallest: 10 largest: 3984
0
The current top of the heap is 0x7f109de20527.
Increased by 345 (0x159) Kbyte
Total blocks: 167 Free: 113 Used: 54
Internal unused: total: 1700352 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 177549 average: 1571.0 smallest: 10 largest: 3984
1
The current top of the heap is 0x7f109de26327.
Increased by 368 (0x170) Kbyte
Total blocks: 169 Free: 117 Used: 52
Internal unused: total: 1637376 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 189341 average: 1618.0 smallest: 10 largest: 3997
2
The current top of the heap is 0x7f109de28282.
Increased by 376 (0x178) Kbyte
Total blocks: 172 Free: 120 Used: 52
Internal unused: total: 1637376 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 201235 average: 1676.0 smallest: 10 largest: 3998
3
The current top of the heap is 0x7f109de2b188.
Increased by 388 (0x184) Kbyte
Total blocks: 175 Free: 125 Used: 50
Internal unused: total: 1574400 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 222205 average: 1777.0 smallest: 10 largest: 3999
4
The current top of the heap is 0x7f109de2e095.
Increased by 400 (0x190) Kbyte
Total blocks: 176 Free: 116 Used: 60
Internal unused: total: 1889280 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 189140 average: 1630.0 smallest: 10 largest: 3999
5
The current top of the heap is 0x7f109de2f045.
Increased by 404 (0x194) Kbyte
Total blocks: 176 Free: 128 Used: 48
Internal unused: total: 1511424 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 227231 average: 1775.0 smallest: 10 largest: 4000
6
The current top of the heap is 0x7f109de2f045.
Increased by 404 (0x194) Kbyte
Total blocks: 177 Free: 125 Used: 52
Internal unused: total: 1637376 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 219943 average: 1759.0 smallest: 10 largest: 3999
7
The current top of the heap is 0x7f109de2fff5.
Increased by 407 (0x197) Kbyte
Total blocks: 178 Free: 118 Used: 60
Internal unused: total: 1889280 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 193697 average: 1641.0 smallest: 10 largest: 4000
8
The current top of the heap is 0x7f109de30fa5.
Increased by 411 (0x19b) Kbyte
Total blocks: 178 Free: 130 Used: 48
Internal unused: total: 1511424 average: 31488.0 smallest: 31488 largest: 31488
External unused: total: 237661 average: 1828.0 smallest: 10 largest: 4000
9
The current top of the heap is 0x7f109de30fa5.
Increased by 411 (0x19b) Kbyte
